r2dbc:
  datasources:
    default:
      options:
        driver: pool
        protocol: postgresql
        initialSize: 0  # Initial pool size. Defaults to 10.
        maxSize: 25 # Maximum pool size. Defaults to 10.
        maxIdleTime: PT5m
        backgroundEvictionInterval: PT5m
        minIdle: 0
      url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:example}?preparedStatementCacheQueries=0
      username: ${POSTGRES_USER:postgres}
      password: ${POSTGRES_PASSWORD:root}
      ssl: ${POSTGRES_SSL:false}

datasources:
  migration:
    # Migrations should connect directly to Postgres and do not run through pgBouncer (flyway issue with pgbouncer)
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:example}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:root}
    ssl: ${POSTGRES_SSL:false}

flyway:
  datasources:
    migration:
      enabled: true
      locations: classpath:migrations

jooq:
  r2dbc-datasources:
    default:
      sql-dialect: Postgres
